/**
 * Setup Google Drive OAuth2 — Jalankan SEKALI untuk mendapatkan refresh token
 * ─────────────────────────────────────────────────────────────
 *
 * PERSIAPAN (di Google Cloud Console):
 * 1. Buka https://console.cloud.google.com/apis/credentials
 * 2. Klik "+ CREATE CREDENTIALS" → "OAuth client ID"
 * 3. Application type: "Desktop app"
 * 4. Download JSON → simpan sebagai "oauth2_credentials.json" di folder backend/
 * 5. Pastikan Google Drive API sudah di-enable:
 *    https://console.cloud.google.com/apis/library/drive.googleapis.com
 *
 * CARA PAKAI:
 *   node setup_drive_auth.js
 *
 * Script akan:
 * 1. Buka URL login di terminal
 * 2. Anda login + izinkan akses Drive
 * 3. Copy kode yang muncul, paste di terminal
 * 4. Script simpan refresh token ke .env otomatis
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Load env
require('dotenv').config({ path: path.join(__dirname, '.env') });

async function main() {
    // 1. Cek credentials file
    const credPath = path.join(__dirname, 'oauth2_credentials.json');
    if (!fs.existsSync(credPath)) {
        console.error('\n❌ File oauth2_credentials.json tidak ditemukan!');
        console.error('\nLangkah-langkah:');
        console.error('1. Buka https://console.cloud.google.com/apis/credentials');
        console.error('2. Klik "+ CREATE CREDENTIALS" → "OAuth client ID"');
        console.error('3. Application type: "Desktop app"');
        console.error('4. Download JSON → rename jadi "oauth2_credentials.json"');
        console.error('5. Letakkan di folder backend/');
        console.error('6. Jalankan lagi: node setup_drive_auth.js\n');
        process.exit(1);
    }

    const { google } = require('googleapis');
    const creds = JSON.parse(fs.readFileSync(credPath, 'utf8'));
    const { client_id, client_secret, redirect_uris } = creds.installed || creds.web || {};

    if (!client_id || !client_secret) {
        console.error('❌ Format credentials JSON tidak valid.');
        process.exit(1);
    }

    const oauth2Client = new google.auth.OAuth2(
        client_id,
        client_secret,
        redirect_uris?.[0] || 'urn:ietf:wg:oauth:2.0:oob'
    );

    // 2. Generate auth URL
    const authUrl = oauth2Client.generateAuthUrl({
        access_type: 'offline',
        prompt: 'consent',
        scope: ['https://www.googleapis.com/auth/drive'],
    });

    console.log('\n╔══════════════════════════════════════════════════════╗');
    console.log('║   SETUP GOOGLE DRIVE OAuth2                         ║');
    console.log('╚══════════════════════════════════════════════════════╝');
    console.log('\n1. Buka URL berikut di browser:\n');
    console.log(`   ${authUrl}\n`);
    console.log('2. Login dengan akun Google yang punya folder Drive PESANAN');
    console.log('3. Klik "Izinkan" / "Allow"');
    console.log('4. Copy kode yang muncul, paste di bawah:\n');

    // 3. Minta kode dari user
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const code = await new Promise(resolve => {
        rl.question('Paste kode di sini: ', answer => {
            rl.close();
            resolve(answer.trim());
        });
    });

    // 4. Exchange code for tokens
    try {
        const { tokens } = await oauth2Client.getToken(code);
        console.log('\n✅ Berhasil mendapatkan token!');

        if (!tokens.refresh_token) {
            console.error('⚠️ Refresh token tidak ada. Coba lagi dengan menghapus akses app di:');
            console.error('   https://myaccount.google.com/permissions');
            process.exit(1);
        }

        // 5. Simpan ke .env
        const envPath = path.join(__dirname, '.env');
        let envContent = fs.readFileSync(envPath, 'utf8');

        // Hapus atau update entries lama
        envContent = envContent.replace(/^GOOGLE_OAUTH2_CLIENT_ID=.*$/gm, '');
        envContent = envContent.replace(/^GOOGLE_OAUTH2_CLIENT_SECRET=.*$/gm, '');
        envContent = envContent.replace(/^GOOGLE_OAUTH2_REFRESH_TOKEN=.*$/gm, '');

        // Tambah entries baru
        const oauthConfig = `
# ═══════════════════════════════════════════════════
# GOOGLE DRIVE OAuth2 (auto-generated by setup_drive_auth.js)
# ═══════════════════════════════════════════════════
GOOGLE_OAUTH2_CLIENT_ID=${client_id}
GOOGLE_OAUTH2_CLIENT_SECRET=${client_secret}
GOOGLE_OAUTH2_REFRESH_TOKEN=${tokens.refresh_token}`;

        envContent = envContent.trimEnd() + '\n' + oauthConfig + '\n';
        fs.writeFileSync(envPath, envContent);

        console.log('\n✅ Token disimpan ke .env!');
        console.log('✅ Google Drive siap digunakan.');
        console.log('\nRestart engine: pm2 restart WA-Engine\n');

    } catch (err) {
        console.error('\n❌ Gagal mendapatkan token:', err.message);
        process.exit(1);
    }
}

main().catch(e => { console.error(e); process.exit(1); });
